




enum GroupViewPermission {
  SEE_NONE
  SEE_SELF
  SEE_ALL
}


type MembershipToGroup {
 	UserId:         ID!
	User: User!
    ViewPermission: GroupViewPermission!   
}

type Group {
    id: ID!
    manager_id: ID!
    name: String!
    description: String!

    directMembers: [MembershipToGroup!]!
    members: [MembershipToGroup!]!

    directManagedGroups: [Group!]!
    directSubGroups: [Group!]!
}

type AnonymousGroup{
    id: ID!
    members: [User!]!
    subgroups: [Group!]!
}

extend type Query {
    
    group(id: ID!): Group!
    anonymousGroup(id: ID!): AnonymousGroup!

    isUserInGroup(userID: ID!, groupID: ID!): Boolean!

    isUserInGroupDirectly(userID: ID!, groupID: ID!): Boolean!    
    canGroupManageGroup(managerID: ID!, groupID: ID!): Boolean!
    canUserManageGroup(managerID: ID!, groupID: ID!): Boolean!
}

