scalar Time

directive @isAdmin on FIELD_DEFINITION

directive @isSelf(userIdField: String, userIdArg: String) on FIELD_DEFINITION 

type User {
    id: ID!
    email: String!
    full_name: String!
    preferred_name: String!
    pronouns: String!
    join_date: Time!
    setup_complete: Boolean!
    archived: Boolean!
    notes: String!
    force_archive: Boolean

    # groups that the user is in and the asker can see. filters based on asker id
    groups: [Group!]! @isSelf
}

extend type Query {
    user(id: ID!): User! @isSelf(userIdArg: "id")  # isStaffOrSelf
    currentUser: User!
}