// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common/plugin.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginStatus int32

const (
	PluginStatus_UNKNOWN      PluginStatus = 0
	PluginStatus_GOOD         PluginStatus = 1
	PluginStatus_DEGRADED     PluginStatus = 2
	PluginStatus_UNCONFIGURED PluginStatus = 3
	PluginStatus_CRASHED      PluginStatus = 4
)

// Enum value maps for PluginStatus.
var (
	PluginStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "GOOD",
		2: "DEGRADED",
		3: "UNCONFIGURED",
		4: "CRASHED",
	}
	PluginStatus_value = map[string]int32{
		"UNKNOWN":      0,
		"GOOD":         1,
		"DEGRADED":     2,
		"UNCONFIGURED": 3,
		"CRASHED":      4,
	}
)

func (x PluginStatus) Enum() *PluginStatus {
	p := new(PluginStatus)
	*p = x
	return p
}

func (x PluginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginStatus) Type() protoreflect.EnumType {
	return &file_common_plugin_proto_enumTypes[0]
}

func (x PluginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginStatus.Descriptor instead.
func (PluginStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	About         string                 `protobuf:"bytes,2,opt,name=about,proto3" json:"about,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"` // 0 if no port needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_common_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

func (x *PluginInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HeartbeatInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PluginStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=common.PluginStatus" json:"status,omitempty"`
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatInfo) Reset() {
	*x = HeartbeatInfo{}
	mi := &file_common_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatInfo) ProtoMessage() {}

func (x *HeartbeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatInfo.ProtoReflect.Descriptor instead.
func (*HeartbeatInfo) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatInfo) GetStatus() PluginStatus {
	if x != nil {
		return x.Status
	}
	return PluginStatus_UNKNOWN
}

func (x *HeartbeatInfo) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_common_plugin_proto protoreflect.FileDescriptor

const file_common_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13common/plugin.proto\x12\x06common\"\a\n" +
	"\x05Empty\"F\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05about\x18\x02 \x01(\tR\x05about\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"d\n" +
	"\rHeartbeatInfo\x12,\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.common.PluginStatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage*R\n" +
	"\fPluginStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04GOOD\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\x10\n" +
	"\fUNCONFIGURED\x10\x03\x12\v\n" +
	"\aCRASHED\x10\x04B&Z$make-backend/internal/plugins/commonb\x06proto3"

var (
	file_common_plugin_proto_rawDescOnce sync.Once
	file_common_plugin_proto_rawDescData []byte
)

func file_common_plugin_proto_rawDescGZIP() []byte {
	file_common_plugin_proto_rawDescOnce.Do(func() {
		file_common_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_plugin_proto_rawDesc), len(file_common_plugin_proto_rawDesc)))
	})
	return file_common_plugin_proto_rawDescData
}

var file_common_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_plugin_proto_goTypes = []any{
	(PluginStatus)(0),     // 0: common.PluginStatus
	(*Empty)(nil),         // 1: common.Empty
	(*PluginInfo)(nil),    // 2: common.PluginInfo
	(*HeartbeatInfo)(nil), // 3: common.HeartbeatInfo
}
var file_common_plugin_proto_depIdxs = []int32{
	0, // 0: common.HeartbeatInfo.status:type_name -> common.PluginStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_plugin_proto_init() }
func file_common_plugin_proto_init() {
	if File_common_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_plugin_proto_rawDesc), len(file_common_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_plugin_proto_goTypes,
		DependencyIndexes: file_common_plugin_proto_depIdxs,
		EnumInfos:         file_common_plugin_proto_enumTypes,
		MessageInfos:      file_common_plugin_proto_msgTypes,
	}.Build()
	File_common_plugin_proto = out.File
	file_common_plugin_proto_goTypes = nil
	file_common_plugin_proto_depIdxs = nil
}
