// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: auth/interface.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "make-backend/internal/plugins/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginResponseType int32

const (
	UserLoginResponseType_USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED UserLoginResponseType = 0
	UserLoginResponseType_USER_CREATED                         UserLoginResponseType = 1
	UserLoginResponseType_USER_FOUND                           UserLoginResponseType = 2
	UserLoginResponseType_USER_ALREADY_EXISTS_OTHER_PROVIDER   UserLoginResponseType = 3
	UserLoginResponseType_ERROR                                UserLoginResponseType = 4
)

// Enum value maps for UserLoginResponseType.
var (
	UserLoginResponseType_name = map[int32]string{
		0: "USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED",
		1: "USER_CREATED",
		2: "USER_FOUND",
		3: "USER_ALREADY_EXISTS_OTHER_PROVIDER",
		4: "ERROR",
	}
	UserLoginResponseType_value = map[string]int32{
		"USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED": 0,
		"USER_CREATED":                         1,
		"USER_FOUND":                           2,
		"USER_ALREADY_EXISTS_OTHER_PROVIDER":   3,
		"ERROR":                                4,
	}
)

func (x UserLoginResponseType) Enum() *UserLoginResponseType {
	p := new(UserLoginResponseType)
	*p = x
	return p
}

func (x UserLoginResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserLoginResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_interface_proto_enumTypes[0].Descriptor()
}

func (UserLoginResponseType) Type() protoreflect.EnumType {
	return &file_auth_interface_proto_enumTypes[0]
}

func (x UserLoginResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserLoginResponseType.Descriptor instead.
func (UserLoginResponseType) EnumDescriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{0}
}

type UserLoginCallback struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName          string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PreferredName     string                 `protobuf:"bytes,3,opt,name=preferred_name,json=preferredName,proto3" json:"preferred_name,omitempty"`
	ProfilePictureUrl string                 `protobuf:"bytes,4,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	PassthroughData   string                 `protobuf:"bytes,5,opt,name=passthrough_data,json=passthroughData,proto3" json:"passthrough_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLoginCallback) Reset() {
	*x = UserLoginCallback{}
	mi := &file_auth_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCallback) ProtoMessage() {}

func (x *UserLoginCallback) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCallback.ProtoReflect.Descriptor instead.
func (*UserLoginCallback) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginCallback) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginCallback) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserLoginCallback) GetPreferredName() string {
	if x != nil {
		return x.PreferredName
	}
	return ""
}

func (x *UserLoginCallback) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *UserLoginCallback) GetPassthroughData() string {
	if x != nil {
		return x.PassthroughData
	}
	return ""
}

type UserLoginStartRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassthroughData string                 `protobuf:"bytes,1,opt,name=passthrough_data,json=passthroughData,proto3" json:"passthrough_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserLoginStartRequest) Reset() {
	*x = UserLoginStartRequest{}
	mi := &file_auth_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginStartRequest) ProtoMessage() {}

func (x *UserLoginStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginStartRequest.ProtoReflect.Descriptor instead.
func (*UserLoginStartRequest) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginStartRequest) GetPassthroughData() string {
	if x != nil {
		return x.PassthroughData
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseType  UserLoginResponseType  `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=auth.UserLoginResponseType" json:"response_type,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_auth_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginResponse) GetResponseType() UserLoginResponseType {
	if x != nil {
		return x.ResponseType
	}
	return UserLoginResponseType_USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED
}

func (x *UserLoginResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLoginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UserLogOffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*UserLogOffRequest_Id
	//	*UserLogOffRequest_Email
	User          isUserLogOffRequest_User `protobuf_oneof:"user"`
	SignedOutUrl  string                   `protobuf:"bytes,3,opt,name=signed_out_url,json=signedOutUrl,proto3" json:"signed_out_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogOffRequest) Reset() {
	*x = UserLogOffRequest{}
	mi := &file_auth_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogOffRequest) ProtoMessage() {}

func (x *UserLogOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogOffRequest.ProtoReflect.Descriptor instead.
func (*UserLogOffRequest) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{3}
}

func (x *UserLogOffRequest) GetUser() isUserLogOffRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserLogOffRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.User.(*UserLogOffRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *UserLogOffRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.User.(*UserLogOffRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UserLogOffRequest) GetSignedOutUrl() string {
	if x != nil {
		return x.SignedOutUrl
	}
	return ""
}

type isUserLogOffRequest_User interface {
	isUserLogOffRequest_User()
}

type UserLogOffRequest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type UserLogOffRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*UserLogOffRequest_Id) isUserLogOffRequest_User() {}

func (*UserLogOffRequest_Email) isUserLogOffRequest_User() {}

type LoginURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginURL) Reset() {
	*x = LoginURL{}
	mi := &file_auth_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginURL) ProtoMessage() {}

func (x *LoginURL) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginURL.ProtoReflect.Descriptor instead.
func (*LoginURL) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{4}
}

func (x *LoginURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RedirectURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectURL) Reset() {
	*x = RedirectURL{}
	mi := &file_auth_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectURL) ProtoMessage() {}

func (x *RedirectURL) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectURL.ProtoReflect.Descriptor instead.
func (*RedirectURL) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{5}
}

func (x *RedirectURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Subserver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subserver) Reset() {
	*x = Subserver{}
	mi := &file_auth_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subserver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subserver) ProtoMessage() {}

func (x *Subserver) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subserver.ProtoReflect.Descriptor instead.
func (*Subserver) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{6}
}

func (x *Subserver) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PluginInitRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CallbackBrokerId uint64                 `protobuf:"varint,1,opt,name=callback_broker_id,json=callbackBrokerId,proto3" json:"callback_broker_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PluginInitRequest) Reset() {
	*x = PluginInitRequest{}
	mi := &file_auth_interface_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInitRequest) ProtoMessage() {}

func (x *PluginInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_interface_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInitRequest.ProtoReflect.Descriptor instead.
func (*PluginInitRequest) Descriptor() ([]byte, []int) {
	return file_auth_interface_proto_rawDescGZIP(), []int{7}
}

func (x *PluginInitRequest) GetCallbackBrokerId() uint64 {
	if x != nil {
		return x.CallbackBrokerId
	}
	return 0
}

var File_auth_interface_proto protoreflect.FileDescriptor

const file_auth_interface_proto_rawDesc = "" +
	"\n" +
	"\x14auth/interface.proto\x12\x04auth\x1a\x13common/plugin.proto\"\xc8\x01\n" +
	"\x11UserLoginCallback\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12%\n" +
	"\x0epreferred_name\x18\x03 \x01(\tR\rpreferredName\x12.\n" +
	"\x13profile_picture_url\x18\x04 \x01(\tR\x11profilePictureUrl\x12)\n" +
	"\x10passthrough_data\x18\x05 \x01(\tR\x0fpassthroughData\"B\n" +
	"\x15UserLoginStartRequest\x12)\n" +
	"\x10passthrough_data\x18\x01 \x01(\tR\x0fpassthroughData\"\x93\x01\n" +
	"\x11UserLoginResponse\x12@\n" +
	"\rresponse_type\x18\x01 \x01(\x0e2\x1b.auth.UserLoginResponseTypeR\fresponseType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"k\n" +
	"\x11UserLogOffRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12$\n" +
	"\x0esigned_out_url\x18\x03 \x01(\tR\fsignedOutUrlB\x06\n" +
	"\x04user\"\x1c\n" +
	"\bLoginURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1f\n" +
	"\vRedirectURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1f\n" +
	"\tSubserver\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\"A\n" +
	"\x11PluginInitRequest\x12,\n" +
	"\x12callback_broker_id\x18\x01 \x01(\x04R\x10callbackBrokerId*\x96\x01\n" +
	"\x15UserLoginResponseType\x12(\n" +
	"$USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fUSER_CREATED\x10\x01\x12\x0e\n" +
	"\n" +
	"USER_FOUND\x10\x02\x12&\n" +
	"\"USER_ALREADY_EXISTS_OTHER_PROVIDER\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\xae\x02\n" +
	"\n" +
	"AuthPlugin\x128\n" +
	"\x04Info\x12\x1c.common.PluginInitialMessage\x1a\x12.common.PluginInfo\x121\n" +
	"\tHeartbeat\x12\r.common.Empty\x1a\x15.common.HeartbeatInfo\x12:\n" +
	"\vGetLoginURL\x12\x1b.auth.UserLoginStartRequest\x1a\x0e.auth.LoginURL\x120\n" +
	"\x06Logout\x12\x17.auth.UserLogOffRequest\x1a\r.common.Empty\x12E\n" +
	"\x1binternalInitializeCallbacks\x12\x17.auth.PluginInitRequest\x1a\r.common.Empty2\x8a\x01\n" +
	"\x13AuthCallbackService\x12:\n" +
	"\fUserLoggedIn\x12\x17.auth.UserLoginCallback\x1a\x11.auth.RedirectURL\x127\n" +
	"\rUserLoggedOut\x12\x17.auth.UserLogOffRequest\x1a\r.common.EmptyB$Z\"make-backend/internal/plugins/authb\x06proto3"

var (
	file_auth_interface_proto_rawDescOnce sync.Once
	file_auth_interface_proto_rawDescData []byte
)

func file_auth_interface_proto_rawDescGZIP() []byte {
	file_auth_interface_proto_rawDescOnce.Do(func() {
		file_auth_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_interface_proto_rawDesc), len(file_auth_interface_proto_rawDesc)))
	})
	return file_auth_interface_proto_rawDescData
}

var file_auth_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_auth_interface_proto_goTypes = []any{
	(UserLoginResponseType)(0),          // 0: auth.UserLoginResponseType
	(*UserLoginCallback)(nil),           // 1: auth.UserLoginCallback
	(*UserLoginStartRequest)(nil),       // 2: auth.UserLoginStartRequest
	(*UserLoginResponse)(nil),           // 3: auth.UserLoginResponse
	(*UserLogOffRequest)(nil),           // 4: auth.UserLogOffRequest
	(*LoginURL)(nil),                    // 5: auth.LoginURL
	(*RedirectURL)(nil),                 // 6: auth.RedirectURL
	(*Subserver)(nil),                   // 7: auth.Subserver
	(*PluginInitRequest)(nil),           // 8: auth.PluginInitRequest
	(*common.PluginInitialMessage)(nil), // 9: common.PluginInitialMessage
	(*common.Empty)(nil),                // 10: common.Empty
	(*common.PluginInfo)(nil),           // 11: common.PluginInfo
	(*common.HeartbeatInfo)(nil),        // 12: common.HeartbeatInfo
}
var file_auth_interface_proto_depIdxs = []int32{
	0,  // 0: auth.UserLoginResponse.response_type:type_name -> auth.UserLoginResponseType
	9,  // 1: auth.AuthPlugin.Info:input_type -> common.PluginInitialMessage
	10, // 2: auth.AuthPlugin.Heartbeat:input_type -> common.Empty
	2,  // 3: auth.AuthPlugin.GetLoginURL:input_type -> auth.UserLoginStartRequest
	4,  // 4: auth.AuthPlugin.Logout:input_type -> auth.UserLogOffRequest
	8,  // 5: auth.AuthPlugin.internalInitializeCallbacks:input_type -> auth.PluginInitRequest
	1,  // 6: auth.AuthCallbackService.UserLoggedIn:input_type -> auth.UserLoginCallback
	4,  // 7: auth.AuthCallbackService.UserLoggedOut:input_type -> auth.UserLogOffRequest
	11, // 8: auth.AuthPlugin.Info:output_type -> common.PluginInfo
	12, // 9: auth.AuthPlugin.Heartbeat:output_type -> common.HeartbeatInfo
	5,  // 10: auth.AuthPlugin.GetLoginURL:output_type -> auth.LoginURL
	10, // 11: auth.AuthPlugin.Logout:output_type -> common.Empty
	10, // 12: auth.AuthPlugin.internalInitializeCallbacks:output_type -> common.Empty
	6,  // 13: auth.AuthCallbackService.UserLoggedIn:output_type -> auth.RedirectURL
	10, // 14: auth.AuthCallbackService.UserLoggedOut:output_type -> common.Empty
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_interface_proto_init() }
func file_auth_interface_proto_init() {
	if File_auth_interface_proto != nil {
		return
	}
	file_auth_interface_proto_msgTypes[3].OneofWrappers = []any{
		(*UserLogOffRequest_Id)(nil),
		(*UserLogOffRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_interface_proto_rawDesc), len(file_auth_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_auth_interface_proto_goTypes,
		DependencyIndexes: file_auth_interface_proto_depIdxs,
		EnumInfos:         file_auth_interface_proto_enumTypes,
		MessageInfos:      file_auth_interface_proto_msgTypes,
	}.Build()
	File_auth_interface_proto = out.File
	file_auth_interface_proto_goTypes = nil
	file_auth_interface_proto_depIdxs = nil
}
