// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: interface.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserLoginResponseType int32

const (
	UserLoginResponseType_USER_CREATED                       UserLoginResponseType = 0
	UserLoginResponseType_USER_FOUND                         UserLoginResponseType = 1
	UserLoginResponseType_USER_ALREADY_EXISTS_OTHER_Provider UserLoginResponseType = 2
	UserLoginResponseType_ERROR                              UserLoginResponseType = 3
)

// Enum value maps for UserLoginResponseType.
var (
	UserLoginResponseType_name = map[int32]string{
		0: "USER_CREATED",
		1: "USER_FOUND",
		2: "USER_ALREADY_EXISTS_OTHER_Provider",
		3: "ERROR",
	}
	UserLoginResponseType_value = map[string]int32{
		"USER_CREATED":                       0,
		"USER_FOUND":                         1,
		"USER_ALREADY_EXISTS_OTHER_Provider": 2,
		"ERROR":                              3,
	}
)

func (x UserLoginResponseType) Enum() *UserLoginResponseType {
	p := new(UserLoginResponseType)
	*p = x
	return p
}

func (x UserLoginResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserLoginResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_interface_proto_enumTypes[0].Descriptor()
}

func (UserLoginResponseType) Type() protoreflect.EnumType {
	return &file_interface_proto_enumTypes[0]
}

func (x UserLoginResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserLoginResponseType.Descriptor instead.
func (UserLoginResponseType) EnumDescriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{0}
}

type UserLoginCallback struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FullName          string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PreferredName     string                 `protobuf:"bytes,3,opt,name=preferred_name,json=preferredName,proto3" json:"preferred_name,omitempty"`
	ProfilePictureUrl string                 `protobuf:"bytes,4,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	PassthroughData   string                 `protobuf:"bytes,5,opt,name=passthrough_data,json=passthroughData,proto3" json:"passthrough_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLoginCallback) Reset() {
	*x = UserLoginCallback{}
	mi := &file_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginCallback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCallback) ProtoMessage() {}

func (x *UserLoginCallback) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCallback.ProtoReflect.Descriptor instead.
func (*UserLoginCallback) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{0}
}

func (x *UserLoginCallback) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserLoginCallback) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserLoginCallback) GetPreferredName() string {
	if x != nil {
		return x.PreferredName
	}
	return ""
}

func (x *UserLoginCallback) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

func (x *UserLoginCallback) GetPassthroughData() string {
	if x != nil {
		return x.PassthroughData
	}
	return ""
}

// user clicks login button
// user selects login provider
// forward to provider to do the actual auth
// provider gets back to us and hands back passthrough data
type UserLoginStartRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PassthroughData string                 `protobuf:"bytes,1,opt,name=passthrough_data,json=passthroughData,proto3" json:"passthrough_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserLoginStartRequest) Reset() {
	*x = UserLoginStartRequest{}
	mi := &file_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginStartRequest) ProtoMessage() {}

func (x *UserLoginStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginStartRequest.ProtoReflect.Descriptor instead.
func (*UserLoginStartRequest) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginStartRequest) GetPassthroughData() string {
	if x != nil {
		return x.PassthroughData
	}
	return ""
}

type UserLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseType  UserLoginResponseType  `protobuf:"varint,1,opt,name=response_type,json=responseType,proto3,enum=auth_plugin.UserLoginResponseType" json:"response_type,omitempty"`
	UserCreated   bool                   `protobuf:"varint,2,opt,name=user_created,json=userCreated,proto3" json:"user_created,omitempty"`
	UserId        int32                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResponse) Reset() {
	*x = UserLoginResponse{}
	mi := &file_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResponse) ProtoMessage() {}

func (x *UserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResponse.ProtoReflect.Descriptor instead.
func (*UserLoginResponse) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginResponse) GetResponseType() UserLoginResponseType {
	if x != nil {
		return x.ResponseType
	}
	return UserLoginResponseType_USER_CREATED
}

func (x *UserLoginResponse) GetUserCreated() bool {
	if x != nil {
		return x.UserCreated
	}
	return false
}

func (x *UserLoginResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLoginResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UserLogOffRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*UserLogOffRequest_Id
	//	*UserLogOffRequest_Email
	User          isUserLogOffRequest_User `protobuf_oneof:"user"`
	SignedOutUrl  string                   `protobuf:"bytes,3,opt,name=signed_out_url,json=signedOutUrl,proto3" json:"signed_out_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLogOffRequest) Reset() {
	*x = UserLogOffRequest{}
	mi := &file_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogOffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogOffRequest) ProtoMessage() {}

func (x *UserLogOffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogOffRequest.ProtoReflect.Descriptor instead.
func (*UserLogOffRequest) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{3}
}

func (x *UserLogOffRequest) GetUser() isUserLogOffRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserLogOffRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.User.(*UserLogOffRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *UserLogOffRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.User.(*UserLogOffRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *UserLogOffRequest) GetSignedOutUrl() string {
	if x != nil {
		return x.SignedOutUrl
	}
	return ""
}

type isUserLogOffRequest_User interface {
	isUserLogOffRequest_User()
}

type UserLogOffRequest_Id struct {
	Id int32 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type UserLogOffRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

func (*UserLogOffRequest_Id) isUserLogOffRequest_User() {}

func (*UserLogOffRequest_Email) isUserLogOffRequest_User() {}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{4}
}

type LoginURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginURL) Reset() {
	*x = LoginURL{}
	mi := &file_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginURL) ProtoMessage() {}

func (x *LoginURL) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginURL.ProtoReflect.Descriptor instead.
func (*LoginURL) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{5}
}

func (x *LoginURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RedirectURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectURL) Reset() {
	*x = RedirectURL{}
	mi := &file_interface_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectURL) ProtoMessage() {}

func (x *RedirectURL) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectURL.ProtoReflect.Descriptor instead.
func (*RedirectURL) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{6}
}

func (x *RedirectURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_interface_proto protoreflect.FileDescriptor

const file_interface_proto_rawDesc = "" +
	"\n" +
	"\x0finterface.proto\x12\vauth_plugin\"\xc8\x01\n" +
	"\x11UserLoginCallback\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12%\n" +
	"\x0epreferred_name\x18\x03 \x01(\tR\rpreferredName\x12.\n" +
	"\x13profile_picture_url\x18\x04 \x01(\tR\x11profilePictureUrl\x12)\n" +
	"\x10passthrough_data\x18\x05 \x01(\tR\x0fpassthroughData\"B\n" +
	"\x15UserLoginStartRequest\x12)\n" +
	"\x10passthrough_data\x18\x01 \x01(\tR\x0fpassthroughData\"\xbd\x01\n" +
	"\x11UserLoginResponse\x12G\n" +
	"\rresponse_type\x18\x01 \x01(\x0e2\".auth_plugin.UserLoginResponseTypeR\fresponseType\x12!\n" +
	"\fuser_created\x18\x02 \x01(\bR\vuserCreated\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x05R\x06userId\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"k\n" +
	"\x11UserLogOffRequest\x12\x10\n" +
	"\x02id\x18\x01 \x01(\x05H\x00R\x02id\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12$\n" +
	"\x0esigned_out_url\x18\x03 \x01(\tR\fsignedOutUrlB\x06\n" +
	"\x04user\"\a\n" +
	"\x05Empty\"\x1c\n" +
	"\bLoginURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x1f\n" +
	"\vRedirectURL\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url*l\n" +
	"\x15UserLoginResponseType\x12\x10\n" +
	"\fUSER_CREATED\x10\x00\x12\x0e\n" +
	"\n" +
	"USER_FOUND\x10\x01\x12&\n" +
	"\"USER_ALREADY_EXISTS_OTHER_Provider\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x032\x94\x01\n" +
	"\n" +
	"AuthPlugin\x12H\n" +
	"\vGetLoginURL\x12\".auth_plugin.UserLoginStartRequest\x1a\x15.auth_plugin.LoginURL\x12<\n" +
	"\x06Logout\x12\x1e.auth_plugin.UserLogOffRequest\x1a\x12.auth_plugin.Empty2\xa4\x01\n" +
	"\x13AuthCallbackService\x12H\n" +
	"\fUserLoggedIn\x12\x1e.auth_plugin.UserLoginCallback\x1a\x18.auth_plugin.RedirectURL\x12C\n" +
	"\rUserLoggedOut\x12\x1e.auth_plugin.UserLogOffRequest\x1a\x12.auth_plugin.EmptyB6Z4github.com/MakeACS/make-backend/internal/plugin/authb\x06proto3"

var (
	file_interface_proto_rawDescOnce sync.Once
	file_interface_proto_rawDescData []byte
)

func file_interface_proto_rawDescGZIP() []byte {
	file_interface_proto_rawDescOnce.Do(func() {
		file_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interface_proto_rawDesc), len(file_interface_proto_rawDesc)))
	})
	return file_interface_proto_rawDescData
}

var file_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_interface_proto_goTypes = []any{
	(UserLoginResponseType)(0),    // 0: auth_plugin.UserLoginResponseType
	(*UserLoginCallback)(nil),     // 1: auth_plugin.UserLoginCallback
	(*UserLoginStartRequest)(nil), // 2: auth_plugin.UserLoginStartRequest
	(*UserLoginResponse)(nil),     // 3: auth_plugin.UserLoginResponse
	(*UserLogOffRequest)(nil),     // 4: auth_plugin.UserLogOffRequest
	(*Empty)(nil),                 // 5: auth_plugin.Empty
	(*LoginURL)(nil),              // 6: auth_plugin.LoginURL
	(*RedirectURL)(nil),           // 7: auth_plugin.RedirectURL
}
var file_interface_proto_depIdxs = []int32{
	0, // 0: auth_plugin.UserLoginResponse.response_type:type_name -> auth_plugin.UserLoginResponseType
	2, // 1: auth_plugin.AuthPlugin.GetLoginURL:input_type -> auth_plugin.UserLoginStartRequest
	4, // 2: auth_plugin.AuthPlugin.Logout:input_type -> auth_plugin.UserLogOffRequest
	1, // 3: auth_plugin.AuthCallbackService.UserLoggedIn:input_type -> auth_plugin.UserLoginCallback
	4, // 4: auth_plugin.AuthCallbackService.UserLoggedOut:input_type -> auth_plugin.UserLogOffRequest
	6, // 5: auth_plugin.AuthPlugin.GetLoginURL:output_type -> auth_plugin.LoginURL
	5, // 6: auth_plugin.AuthPlugin.Logout:output_type -> auth_plugin.Empty
	7, // 7: auth_plugin.AuthCallbackService.UserLoggedIn:output_type -> auth_plugin.RedirectURL
	5, // 8: auth_plugin.AuthCallbackService.UserLoggedOut:output_type -> auth_plugin.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_interface_proto_init() }
func file_interface_proto_init() {
	if File_interface_proto != nil {
		return
	}
	file_interface_proto_msgTypes[3].OneofWrappers = []any{
		(*UserLogOffRequest_Id)(nil),
		(*UserLogOffRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interface_proto_rawDesc), len(file_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_interface_proto_goTypes,
		DependencyIndexes: file_interface_proto_depIdxs,
		EnumInfos:         file_interface_proto_enumTypes,
		MessageInfos:      file_interface_proto_msgTypes,
	}.Build()
	File_interface_proto = out.File
	file_interface_proto_goTypes = nil
	file_interface_proto_depIdxs = nil
}
