// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: interface.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPlugin_GetLoginURL_FullMethodName = "/auth_plugin.AuthPlugin/GetLoginURL"
	AuthPlugin_Logout_FullMethodName      = "/auth_plugin.AuthPlugin/Logout"
)

// AuthPluginClient is the client API for AuthPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPluginClient interface {
	// ask a provider to start the login process
	GetLoginURL(ctx context.Context, in *UserLoginStartRequest, opts ...grpc.CallOption) (*LoginURL, error)
	// ask provider to log out a user
	Logout(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*Empty, error)
}

type authPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginClient(cc grpc.ClientConnInterface) AuthPluginClient {
	return &authPluginClient{cc}
}

func (c *authPluginClient) GetLoginURL(ctx context.Context, in *UserLoginStartRequest, opts ...grpc.CallOption) (*LoginURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginURL)
	err := c.cc.Invoke(ctx, AuthPlugin_GetLoginURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) Logout(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuthPlugin_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServer is the server API for AuthPlugin service.
// All implementations must embed UnimplementedAuthPluginServer
// for forward compatibility.
type AuthPluginServer interface {
	// ask a provider to start the login process
	GetLoginURL(context.Context, *UserLoginStartRequest) (*LoginURL, error)
	// ask provider to log out a user
	Logout(context.Context, *UserLogOffRequest) (*Empty, error)
	mustEmbedUnimplementedAuthPluginServer()
}

// UnimplementedAuthPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServer struct{}

func (UnimplementedAuthPluginServer) GetLoginURL(context.Context, *UserLoginStartRequest) (*LoginURL, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoginURL not implemented")
}
func (UnimplementedAuthPluginServer) Logout(context.Context, *UserLogOffRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthPluginServer) mustEmbedUnimplementedAuthPluginServer() {}
func (UnimplementedAuthPluginServer) testEmbeddedByValue()                    {}

// UnsafeAuthPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServer will
// result in compilation errors.
type UnsafeAuthPluginServer interface {
	mustEmbedUnimplementedAuthPluginServer()
}

func RegisterAuthPluginServer(s grpc.ServiceRegistrar, srv AuthPluginServer) {
	// If the following call panics, it indicates UnimplementedAuthPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPlugin_ServiceDesc, srv)
}

func _AuthPlugin_GetLoginURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).GetLoginURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_GetLoginURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).GetLoginURL(ctx, req.(*UserLoginStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).Logout(ctx, req.(*UserLogOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPlugin_ServiceDesc is the grpc.ServiceDesc for AuthPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_plugin.AuthPlugin",
	HandlerType: (*AuthPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLoginURL",
			Handler:    _AuthPlugin_GetLoginURL_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthPlugin_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface.proto",
}

const (
	AuthCallbackService_UserLoggedIn_FullMethodName  = "/auth_plugin.AuthCallbackService/UserLoggedIn"
	AuthCallbackService_UserLoggedOut_FullMethodName = "/auth_plugin.AuthCallbackService/UserLoggedOut"
)

// AuthCallbackServiceClient is the client API for AuthCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthCallbackServiceClient interface {
	// told to the base server when a user finishes logging in
	UserLoggedIn(ctx context.Context, in *UserLoginCallback, opts ...grpc.CallOption) (*RedirectURL, error)
	// told to the base server when a user finishes logging out
	UserLoggedOut(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*Empty, error)
}

type authCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthCallbackServiceClient(cc grpc.ClientConnInterface) AuthCallbackServiceClient {
	return &authCallbackServiceClient{cc}
}

func (c *authCallbackServiceClient) UserLoggedIn(ctx context.Context, in *UserLoginCallback, opts ...grpc.CallOption) (*RedirectURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectURL)
	err := c.cc.Invoke(ctx, AuthCallbackService_UserLoggedIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCallbackServiceClient) UserLoggedOut(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AuthCallbackService_UserLoggedOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCallbackServiceServer is the server API for AuthCallbackService service.
// All implementations must embed UnimplementedAuthCallbackServiceServer
// for forward compatibility.
type AuthCallbackServiceServer interface {
	// told to the base server when a user finishes logging in
	UserLoggedIn(context.Context, *UserLoginCallback) (*RedirectURL, error)
	// told to the base server when a user finishes logging out
	UserLoggedOut(context.Context, *UserLogOffRequest) (*Empty, error)
	mustEmbedUnimplementedAuthCallbackServiceServer()
}

// UnimplementedAuthCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthCallbackServiceServer struct{}

func (UnimplementedAuthCallbackServiceServer) UserLoggedIn(context.Context, *UserLoginCallback) (*RedirectURL, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLoggedIn not implemented")
}
func (UnimplementedAuthCallbackServiceServer) UserLoggedOut(context.Context, *UserLogOffRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLoggedOut not implemented")
}
func (UnimplementedAuthCallbackServiceServer) mustEmbedUnimplementedAuthCallbackServiceServer() {}
func (UnimplementedAuthCallbackServiceServer) testEmbeddedByValue()                             {}

// UnsafeAuthCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthCallbackServiceServer will
// result in compilation errors.
type UnsafeAuthCallbackServiceServer interface {
	mustEmbedUnimplementedAuthCallbackServiceServer()
}

func RegisterAuthCallbackServiceServer(s grpc.ServiceRegistrar, srv AuthCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthCallbackService_ServiceDesc, srv)
}

func _AuthCallbackService_UserLoggedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginCallback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCallbackServiceServer).UserLoggedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCallbackService_UserLoggedIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCallbackServiceServer).UserLoggedIn(ctx, req.(*UserLoginCallback))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthCallbackService_UserLoggedOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCallbackServiceServer).UserLoggedOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCallbackService_UserLoggedOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCallbackServiceServer).UserLoggedOut(ctx, req.(*UserLogOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthCallbackService_ServiceDesc is the grpc.ServiceDesc for AuthCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_plugin.AuthCallbackService",
	HandlerType: (*AuthCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLoggedIn",
			Handler:    _AuthCallbackService_UserLoggedIn_Handler,
		},
		{
			MethodName: "UserLoggedOut",
			Handler:    _AuthCallbackService_UserLoggedOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface.proto",
}
