syntax="proto3";

package auth_plugin;

option go_package = 'github.com/MakeACS/make-backend/internal/plugin/auth';

message UserLoginCallback {
  string email = 1;
  string full_name = 2;
  string preferred_name = 3;
  string profile_picture_url = 4;
  string passthrough_data = 5;
}

message UserLoginStartRequest {
  string passthrough_data = 1;
}

enum UserLoginResponseType {
  USER_LOGIN_RESPONSE_TYPE_UNSPECIFIED = 0;
  USER_CREATED = 1;
  USER_FOUND = 2;
  USER_ALREADY_EXISTS_OTHER_PROVIDER = 3;
  ERROR = 4;
}

message UserLoginResponse {
  UserLoginResponseType response_type = 1;
  int32 user_id = 2;
  string error_message = 3;
}

message UserLogOffRequest {
  oneof user {
    int32 id = 1;
    string email = 2;
  }
  string signed_out_url = 3;
}

message Empty {}
message LoginURL { string url = 1; }
message RedirectURL { string url = 1; }
message Subserver{
    int32 port = 1;
}
message PluginInitRequest {
  uint64 callback_broker_id = 1;
}

service AuthPlugin {
  rpc Initialize(PluginInitRequest) returns (Empty);
  rpc GetLoginURL(UserLoginStartRequest) returns (LoginURL);
  rpc Logout(UserLogOffRequest) returns (Empty);
}

service AuthCallbackService {
  rpc UserLoggedIn(UserLoginCallback) returns (RedirectURL);
  rpc UserLoggedOut(UserLogOffRequest) returns (Empty);
}
