// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: auth/interface.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "make-backend/internal/plugins/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthPlugin_Info_FullMethodName                        = "/auth.AuthPlugin/Info"
	AuthPlugin_GetAuthDescription_FullMethodName          = "/auth.AuthPlugin/GetAuthDescription"
	AuthPlugin_Heartbeat_FullMethodName                   = "/auth.AuthPlugin/Heartbeat"
	AuthPlugin_GetLoginRequest_FullMethodName             = "/auth.AuthPlugin/GetLoginRequest"
	AuthPlugin_Logout_FullMethodName                      = "/auth.AuthPlugin/Logout"
	AuthPlugin_InternalInitializeCallbacks_FullMethodName = "/auth.AuthPlugin/internalInitializeCallbacks"
)

// AuthPluginClient is the client API for AuthPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthPluginClient interface {
	Info(ctx context.Context, in *common.PluginInitialMessage, opts ...grpc.CallOption) (*common.PluginInfo, error)
	GetAuthDescription(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AuthDescription, error)
	Heartbeat(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.HeartbeatInfo, error)
	GetLoginRequest(ctx context.Context, in *UserLoginStartRequest, opts ...grpc.CallOption) (*LoginRequest, error)
	Logout(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*common.Empty, error)
	// end user doesn't have to use this, they have to implement register callback in go land. this is intercepted by the rpc server and the details taken care of for the actual plugin
	InternalInitializeCallbacks(ctx context.Context, in *PluginInitRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type authPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthPluginClient(cc grpc.ClientConnInterface) AuthPluginClient {
	return &authPluginClient{cc}
}

func (c *authPluginClient) Info(ctx context.Context, in *common.PluginInitialMessage, opts ...grpc.CallOption) (*common.PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.PluginInfo)
	err := c.cc.Invoke(ctx, AuthPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) GetAuthDescription(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*AuthDescription, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthDescription)
	err := c.cc.Invoke(ctx, AuthPlugin_GetAuthDescription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) Heartbeat(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.HeartbeatInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.HeartbeatInfo)
	err := c.cc.Invoke(ctx, AuthPlugin_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) GetLoginRequest(ctx context.Context, in *UserLoginStartRequest, opts ...grpc.CallOption) (*LoginRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginRequest)
	err := c.cc.Invoke(ctx, AuthPlugin_GetLoginRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) Logout(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthPlugin_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authPluginClient) InternalInitializeCallbacks(ctx context.Context, in *PluginInitRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthPlugin_InternalInitializeCallbacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthPluginServer is the server API for AuthPlugin service.
// All implementations must embed UnimplementedAuthPluginServer
// for forward compatibility.
type AuthPluginServer interface {
	Info(context.Context, *common.PluginInitialMessage) (*common.PluginInfo, error)
	GetAuthDescription(context.Context, *common.Empty) (*AuthDescription, error)
	Heartbeat(context.Context, *common.Empty) (*common.HeartbeatInfo, error)
	GetLoginRequest(context.Context, *UserLoginStartRequest) (*LoginRequest, error)
	Logout(context.Context, *UserLogOffRequest) (*common.Empty, error)
	// end user doesn't have to use this, they have to implement register callback in go land. this is intercepted by the rpc server and the details taken care of for the actual plugin
	InternalInitializeCallbacks(context.Context, *PluginInitRequest) (*common.Empty, error)
	mustEmbedUnimplementedAuthPluginServer()
}

// UnimplementedAuthPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthPluginServer struct{}

func (UnimplementedAuthPluginServer) Info(context.Context, *common.PluginInitialMessage) (*common.PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedAuthPluginServer) GetAuthDescription(context.Context, *common.Empty) (*AuthDescription, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthDescription not implemented")
}
func (UnimplementedAuthPluginServer) Heartbeat(context.Context, *common.Empty) (*common.HeartbeatInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAuthPluginServer) GetLoginRequest(context.Context, *UserLoginStartRequest) (*LoginRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoginRequest not implemented")
}
func (UnimplementedAuthPluginServer) Logout(context.Context, *UserLogOffRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedAuthPluginServer) InternalInitializeCallbacks(context.Context, *PluginInitRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method InternalInitializeCallbacks not implemented")
}
func (UnimplementedAuthPluginServer) mustEmbedUnimplementedAuthPluginServer() {}
func (UnimplementedAuthPluginServer) testEmbeddedByValue()                    {}

// UnsafeAuthPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthPluginServer will
// result in compilation errors.
type UnsafeAuthPluginServer interface {
	mustEmbedUnimplementedAuthPluginServer()
}

func RegisterAuthPluginServer(s grpc.ServiceRegistrar, srv AuthPluginServer) {
	// If the following call panics, it indicates UnimplementedAuthPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthPlugin_ServiceDesc, srv)
}

func _AuthPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.PluginInitialMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).Info(ctx, req.(*common.PluginInitialMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_GetAuthDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).GetAuthDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_GetAuthDescription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).GetAuthDescription(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).Heartbeat(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_GetLoginRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).GetLoginRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_GetLoginRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).GetLoginRequest(ctx, req.(*UserLoginStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).Logout(ctx, req.(*UserLogOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthPlugin_InternalInitializeCallbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthPluginServer).InternalInitializeCallbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthPlugin_InternalInitializeCallbacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthPluginServer).InternalInitializeCallbacks(ctx, req.(*PluginInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthPlugin_ServiceDesc is the grpc.ServiceDesc for AuthPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthPlugin",
	HandlerType: (*AuthPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _AuthPlugin_Info_Handler,
		},
		{
			MethodName: "GetAuthDescription",
			Handler:    _AuthPlugin_GetAuthDescription_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AuthPlugin_Heartbeat_Handler,
		},
		{
			MethodName: "GetLoginRequest",
			Handler:    _AuthPlugin_GetLoginRequest_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _AuthPlugin_Logout_Handler,
		},
		{
			MethodName: "internalInitializeCallbacks",
			Handler:    _AuthPlugin_InternalInitializeCallbacks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/interface.proto",
}

const (
	AuthCallbackService_UserLoggedIn_FullMethodName  = "/auth.AuthCallbackService/UserLoggedIn"
	AuthCallbackService_UserLoggedOut_FullMethodName = "/auth.AuthCallbackService/UserLoggedOut"
)

// AuthCallbackServiceClient is the client API for AuthCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthCallbackServiceClient interface {
	UserLoggedIn(ctx context.Context, in *UserLoginCallback, opts ...grpc.CallOption) (*RedirectURL, error)
	UserLoggedOut(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*common.Empty, error)
}

type authCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthCallbackServiceClient(cc grpc.ClientConnInterface) AuthCallbackServiceClient {
	return &authCallbackServiceClient{cc}
}

func (c *authCallbackServiceClient) UserLoggedIn(ctx context.Context, in *UserLoginCallback, opts ...grpc.CallOption) (*RedirectURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedirectURL)
	err := c.cc.Invoke(ctx, AuthCallbackService_UserLoggedIn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authCallbackServiceClient) UserLoggedOut(ctx context.Context, in *UserLogOffRequest, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AuthCallbackService_UserLoggedOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthCallbackServiceServer is the server API for AuthCallbackService service.
// All implementations must embed UnimplementedAuthCallbackServiceServer
// for forward compatibility.
type AuthCallbackServiceServer interface {
	UserLoggedIn(context.Context, *UserLoginCallback) (*RedirectURL, error)
	UserLoggedOut(context.Context, *UserLogOffRequest) (*common.Empty, error)
	mustEmbedUnimplementedAuthCallbackServiceServer()
}

// UnimplementedAuthCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthCallbackServiceServer struct{}

func (UnimplementedAuthCallbackServiceServer) UserLoggedIn(context.Context, *UserLoginCallback) (*RedirectURL, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLoggedIn not implemented")
}
func (UnimplementedAuthCallbackServiceServer) UserLoggedOut(context.Context, *UserLogOffRequest) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserLoggedOut not implemented")
}
func (UnimplementedAuthCallbackServiceServer) mustEmbedUnimplementedAuthCallbackServiceServer() {}
func (UnimplementedAuthCallbackServiceServer) testEmbeddedByValue()                             {}

// UnsafeAuthCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthCallbackServiceServer will
// result in compilation errors.
type UnsafeAuthCallbackServiceServer interface {
	mustEmbedUnimplementedAuthCallbackServiceServer()
}

func RegisterAuthCallbackServiceServer(s grpc.ServiceRegistrar, srv AuthCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthCallbackService_ServiceDesc, srv)
}

func _AuthCallbackService_UserLoggedIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginCallback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCallbackServiceServer).UserLoggedIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCallbackService_UserLoggedIn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCallbackServiceServer).UserLoggedIn(ctx, req.(*UserLoginCallback))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthCallbackService_UserLoggedOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogOffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthCallbackServiceServer).UserLoggedOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthCallbackService_UserLoggedOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthCallbackServiceServer).UserLoggedOut(ctx, req.(*UserLogOffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthCallbackService_ServiceDesc is the grpc.ServiceDesc for AuthCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthCallbackService",
	HandlerType: (*AuthCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLoggedIn",
			Handler:    _AuthCallbackService_UserLoggedIn_Handler,
		},
		{
			MethodName: "UserLoggedOut",
			Handler:    _AuthCallbackService_UserLoggedOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/interface.proto",
}
