package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/database/models"
)

// Type is the resolver for the type field.
func (r *accessComponentResolver) Type(ctx context.Context, obj *models.AccessComponent) (int, error) {
	return int(obj.Type), nil
}

// AccessComponent returns AccessComponentResolver implementation.
func (r *Resolver) AccessComponent() AccessComponentResolver { return &accessComponentResolver{r} }

type accessComponentResolver struct{ *Resolver }
