package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/database/models"
)

// DayOfWeek is the resolver for the day_of_week field.
func (r *defaultHoursResolver) DayOfWeek(ctx context.Context, obj *models.DefaultHours) (int32, error) {
	panic(fmt.Errorf("not implemented: DayOfWeek - day_of_week"))
}

// DefaultHours returns DefaultHoursResolver implementation.
func (r *Resolver) DefaultHours() DefaultHoursResolver { return &defaultHoursResolver{r} }

type defaultHoursResolver struct{ *Resolver }
