package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/database/models"
)

// Zones is the resolver for the zones field.
func (r *makerspaceResolver) Zones(ctx context.Context, obj *models.Makerspace) ([]*models.Zone, error) {
	zones, err := r.Store.Zones.GetZonesByMakerspaceId(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	return zones, err
}

// CreateMakerspace is the resolver for the createMakerspace field.
func (r *mutationResolver) CreateMakerspace(ctx context.Context, name string, hidden bool) (int, error) {
	id, err := r.Store.Makerspaces.CreateMakerspace(ctx, name, hidden)
	if err != nil {
		return 0, err
	}

	return id, nil
}

// DeleteMakerspace is the resolver for the deleteMakerspace field.
func (r *mutationResolver) DeleteMakerspace(ctx context.Context, id int) (bool, error) {
	success, err := r.Store.Makerspaces.DeleteMakerspace(ctx, id)
	if err != nil {
		return success, err
	}

	return success, err
}

// Makerspace is the resolver for the makerspace field.
func (r *queryResolver) Makerspace(ctx context.Context, id int) (*models.Makerspace, error) {
	makerspace, err := r.Store.Makerspaces.GetMakerspaceById(ctx, id)
	if err != nil {
		return nil, err
	}

	return makerspace, nil
}

// Makerspace returns MakerspaceResolver implementation.
func (r *Resolver) Makerspace() MakerspaceResolver { return &makerspaceResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	makerspaceResolver struct{ *Resolver }
	mutationResolver   struct{ *Resolver }
	queryResolver      struct{ *Resolver }
)
