package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/gql/model"
)

// Makerspace is the resolver for the makerspace field.
func (r *queryResolver) Makerspace(ctx context.Context, id int) (*model.Makerspace, error) {
	panic(fmt.Errorf("not implemented: Makerspace - makerspace"))
}
