package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/database/models"
)

// Correct is the resolver for the correct field.
func (r *optionBlockOptionResolver) Correct(ctx context.Context, obj *models.OptionBlockOption) (*bool, error) {
	panic(fmt.Errorf("not implemented: Correct - correct"))
}

// Blocks is the resolver for the blocks field.
func (r *trainingResolver) Blocks(ctx context.Context, obj *models.Training) ([]models.TrainingBlock, error) {
	return []models.TrainingBlock(obj.Blocks), nil
}

// OptionBlockOption returns OptionBlockOptionResolver implementation.
func (r *Resolver) OptionBlockOption() OptionBlockOptionResolver {
	return &optionBlockOptionResolver{r}
}

// Training returns TrainingResolver implementation.
func (r *Resolver) Training() TrainingResolver { return &trainingResolver{r} }

type (
	optionBlockOptionResolver struct{ *Resolver }
	trainingResolver          struct{ *Resolver }
)
