package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
)

// UpdateStudentProfile is the resolver for the updateStudentProfile field.
func (r *mutationResolver) UpdateStudentProfile(ctx context.Context, userID int, pronouns *string, college *string, expectedGraduation *string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: UpdateStudentProfile - updateStudentProfile"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*models.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models.User, error) {
	auth_user := ctx.Value(auth.UserContextKey{}).(*auth.User)

	user, err := r.Store.Users.GetUserById(ctx, auth_user.Id)

	return user, err
}
