package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/database/models"
)

// Zone is the resolver for the zone field.
func (r *queryResolver) Zone(ctx context.Context, id int) (*models.Zone, error) {
	zone, err := r.Store.Zones.GetZoneById(ctx, id)
	if err != nil {
		return nil, err
	}

	return zone, nil
}

// ZonesByMakerspaceID is the resolver for the zonesByMakerspaceId field.
func (r *queryResolver) ZonesByMakerspaceID(ctx context.Context, makerspaceID int) ([]*models.Zone, error) {
	panic(fmt.Errorf("not implemented: ZonesByMakerspaceID - zonesByMakerspaceId"))
}
