package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/gql/model"
)

// AuthProviders is the resolver for the authProviders field.
func (r *queryResolver) AuthProviders(ctx context.Context) ([]*model.AuthProvider, error) {
	providers := []*model.AuthProvider{}
	for id, p := range r.Plugins.Auth {
		providers = append(providers, &model.AuthProvider{
			Name:     p.Name,
			ImageURL: p.ImageUrl,
			PluginID: id,
		})
	}
	return providers, nil
}
