package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// Type is the resolver for the type field.
func (r *accessComponentResolver) Type(ctx context.Context, obj *models.AccessComponent) (int, error) {
	return int(obj.Type), nil
}

// Device is the resolver for the device field.
func (r *queryResolver) Device(ctx context.Context, id int) (*models.Device, error) {
	dev, err := r.Store.Devices.GetDeviceById(ctx, id)
	if err != nil {
		return nil, err
	}
	return dev, nil
}

// AccessDevice is the resolver for the accessDevice field.
func (r *queryResolver) AccessDevice(ctx context.Context, id int) (*models.AccessDevice, error) {
	dev, err := r.Store.Devices.GetAccessDeviceById(ctx, id)
	if err != nil {
		return nil, err
	}
	return dev, nil
}

// AccessComponent returns gql.AccessComponentResolver implementation.
func (r *Resolver) AccessComponent() gql.AccessComponentResolver { return &accessComponentResolver{r} }

type accessComponentResolver struct{ *Resolver }
