package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// Type is the resolver for the type field.
func (r *accessComponentResolver) Type(ctx context.Context, obj *models.AccessComponent) (int, error) {
	return int(obj.Type), nil
}

// DeviceID is the resolver for the device_id field.
func (r *accessDeviceResolver) DeviceID(ctx context.Context, obj *models.AccessDevice) (int, error) {
	return obj.Id, nil

}

// AccessComponent returns gql.AccessComponentResolver implementation.
func (r *Resolver) AccessComponent() gql.AccessComponentResolver { return &accessComponentResolver{r} }

// AccessDevice returns gql.AccessDeviceResolver implementation.
func (r *Resolver) AccessDevice() gql.AccessDeviceResolver { return &accessDeviceResolver{r} }

type (
	accessComponentResolver struct{ *Resolver }
	accessDeviceResolver    struct{ *Resolver }
)
