package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
)

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, id int) (*models.Group, error) {
	userID := ctx.Value(auth.UserContextKey{}).(int)

	group, err := r.Store.Groups.GetGroupById(ctx, id)
	if err != nil {
		return nil, err
	}
	visible, err := r.Store.Groups.IsGroupVisibleToUser(ctx, userID, group.Id)
	if err != nil {
		return nil, err
	}
	if !visible {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}
	return group, nil
}

// MembersOfGroup is the resolver for the membersOfGroup field.
func (r *queryResolver) MembersOfGroup(ctx context.Context, groupID int) ([]*models.MembershipToGroup, error) {
	askingUserID := ctx.Value(auth.UserContextKey{}).(int)
	visible, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, groupID)
	if err != nil {
		return nil, err
	}
	if !visible {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}

	_, how, err := r.Store.Groups.IsUserInGroup(ctx, askingUserID, groupID)
	if how == models.GroupViewPermission_SeeNone {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}
	if how == models.GroupViewPermission_SeeSelf {
		user, err := r.Store.Users.GetUserById(ctx, askingUserID)
		if err != nil {
			return nil, fmt.Errorf("could not find querying user %w", err)
		}
		return []*models.MembershipToGroup{{
			UserId:         user.Id,
			ViewPermission: how,
		}}, nil
	}
	members, err := r.Store.Groups.GetGroupMembers(ctx, groupID)
	if !visible || how == models.GroupViewPermission_SeeNone {
		return nil, fmt.Errorf("error finding group members: %w", err)
	}
	members2 := []*models.MembershipToGroup{}
	for _, member := range members {
		members2 = append(members2, &member)
	}
	return members2, nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID int, groupID int) (bool, error) {
	askingUserID := ctx.Value(auth.UserContextKey{}).(int)

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, fmt.Errorf("group does not exist or user has invalid permissions to query it")
	}

	in, _, err := r.Store.Groups.IsUserInGroup(ctx, userID, groupID)
	return in, err
}

// IsUserInGroupDirectly is the resolver for the isUserInGroupDirectly field.
func (r *queryResolver) IsUserInGroupDirectly(ctx context.Context, userID int, groupID int) (bool, error) {
	askingUserID := ctx.Value(auth.UserContextKey{}).(int)

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, fmt.Errorf("group does not exist or user has invalid permissions to query it")
	}

	in, _, err := r.Store.Groups.IsUserInGroupDirectly(ctx, userID, groupID)
	return in, err

}

// CanGroupManageGroup is the resolver for the canGroupManageGroup field.
func (r *queryResolver) CanGroupManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	askingUserID := ctx.Value(auth.UserContextKey{}).(int)

	managerVisibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, managerID)
	if err != nil {
		return false, err
	}
	if !managerVisibleToAsker {
		return false, fmt.Errorf("manager group does not exist or user has invalid permissions to query it")
	}
	managedVisibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !managedVisibleToAsker {
		return false, fmt.Errorf("managed group does not exist or user has invalid permissions to query it")
	}
	return r.Store.Groups.CanGroupManageGroup(ctx, managerID, groupID)
}

// CanUserManageGroup is the resolver for the canUserManageGroup field.
func (r *queryResolver) CanUserManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	askingUserID := ctx.Value(auth.UserContextKey{}).(int)

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, fmt.Errorf("group does not exist or user has invalid permissions to query it")
	}
	return r.Store.Groups.CanUserManageGroup(ctx, managerID, groupID)
}
