package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// Members is the resolver for the members field.
func (r *anonymousGroupResolver) Members(ctx context.Context, obj *models.AnonymousGroup) ([]*models.User, error) {
	members, err := r.Store.Groups.UsersInAnonymousGroup(ctx, obj.Id)
	if err != nil {

		return nil, err
	}
	return SliceToPtrSlice(members), nil
}

// Subgroups is the resolver for the subgroups field.
func (r *anonymousGroupResolver) Subgroups(ctx context.Context, obj *models.AnonymousGroup) ([]*models.Group, error) {
	subgroups, err := r.Store.Groups.GroupsInAnonymousGroup(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(subgroups), nil
}

// DirectMembers is the resolver for the directMembers field.
func (r *groupResolver) DirectMembers(ctx context.Context, obj *models.Group) ([]*models.MembershipToGroup, error) {
	panic(fmt.Errorf("not implemented: DirectMembers - directMembers"))
}

// Members is the resolver for the members field.
func (r *groupResolver) Members(ctx context.Context, obj *models.Group) ([]*models.MembershipToGroup, error) {
	userId := auth.UserIDFromContext(ctx)
	if userId == nil {
		return nil, auth.ErrNotAuthenticated
	}

	visible, how, err := r.Store.Groups.IsUserInGroup(ctx, *userId, obj.Id)
	if err != nil {
		return nil, err
	}
	visibleByManager, err := r.Store.Groups.CanUserManageGroup(ctx, *userId, obj.Id)
	if err != nil {
		return nil, err
	}

	visible = visible || visibleByManager
	if !visible {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}
	if how == models.GroupViewPermission_SeeSelf && !visibleByManager {
		m := models.MembershipToGroup{
			UserId:         *userId,
			ViewPermission: models.GroupViewPermission_SeeSelf,
		}
		ms := []*models.MembershipToGroup{
			&m,
		}
		return ms, nil
	}

	// Permission SeeAll or manager level

	members, err := r.Store.Groups.GetGroupMembers(ctx, obj.Id)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(members), nil
}

// DirectManagedGroups is the resolver for the directManagedGroups field.
func (r *groupResolver) DirectManagedGroups(ctx context.Context, obj *models.Group) ([]*models.Group, error) {
	groupIds, err := r.Store.Groups.AllGroupsGroupCanManageDirectly(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	groups := make([]*models.Group, len(groupIds))
	for i, id := range groupIds {
		g, err := r.Store.Groups.GetGroupById(ctx, id)
		if err != nil {
			return nil, err
		}
		groups[i] = g

	}
	return groups, nil
}

// DirectSubGroups is the resolver for the directSubGroups field.
func (r *groupResolver) DirectSubGroups(ctx context.Context, obj *models.Group) ([]*models.Group, error) {
	panic(fmt.Errorf("not implemented: DirectSubGroups - directSubGroups"))
}

// User is the resolver for the User field.
func (r *membershipToGroupResolver) User(ctx context.Context, obj *models.MembershipToGroup) (*models.User, error) {
	return r.Store.Users.GetUserById(ctx, obj.UserId)
}

// SetAnonymousGroupSubgroups is the resolver for the SetAnonymousGroupSubgroups field.
func (r *mutationResolver) SetAnonymousGroupSubgroups(ctx context.Context, agroupID int, subgroups []int) (bool, error) {
	err := r.Store.Groups.SetGroupsForAnonymousGroup(ctx, agroupID, subgroups)
	if err != nil {
		return false, err
	}
	return true, nil
}

// Group is the resolver for the group field.
func (r *queryResolver) Group(ctx context.Context, id int) (*models.Group, error) {
	userId := auth.UserIDFromContext(ctx)
	if userId == nil {
		return nil, auth.ErrNotAuthenticated
	}

	visible, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *userId, id)
	if err != nil {
		return nil, err
	}
	if !visible {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}

	group, err := r.Store.Groups.GetGroupById(ctx, id)
	if err != nil {
		return nil, err
	}
	return group, nil
}

// AnonymousGroup is the resolver for the anonymousGroup field.
func (r *queryResolver) AnonymousGroup(ctx context.Context, id int) (*models.AnonymousGroup, error) {
	ag := models.AnonymousGroup{
		Id: id,
	}
	return &ag, nil
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID int, groupID int) (bool, error) {
	askingUserID := auth.UserIDFromContext(ctx)
	if askingUserID == nil {
		return false, auth.ErrNotAuthenticated
	}

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, models.ErrNoGroupOrWrongPermissions
	}

	in, _, err := r.Store.Groups.IsUserInGroup(ctx, userID, groupID)
	return in, err
}

// IsUserInGroupDirectly is the resolver for the isUserInGroupDirectly field.
func (r *queryResolver) IsUserInGroupDirectly(ctx context.Context, userID int, groupID int) (bool, error) {
	askingUserID := auth.UserIDFromContext(ctx)
	if askingUserID == nil {
		return false, auth.ErrNotAuthenticated
	}

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, models.ErrNoGroupOrWrongPermissions
	}

	in, _, err := r.Store.Groups.IsUserInGroupDirectly(ctx, userID, groupID)
	return in, err
}

// CanGroupManageGroup is the resolver for the canGroupManageGroup field.
func (r *queryResolver) CanGroupManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	askingUserID := auth.UserIDFromContext(ctx)
	if askingUserID == nil {
		return false, auth.ErrNotAuthenticated
	}

	managerVisibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *askingUserID, managerID)
	if err != nil {
		return false, err
	}
	if !managerVisibleToAsker {
		return false, fmt.Errorf("manager group does not exist or user has invalid permissions to query it")
	}
	managedVisibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !managedVisibleToAsker {
		return false, fmt.Errorf("managed group does not exist or user has invalid permissions to query it")
	}

	managedVisibleToManager, err := r.Store.Groups.IsGroupVisibleToGroup(ctx, managerID, groupID)
	if err != nil {
		return false, err
	}
	if !managedVisibleToManager {
		return false, fmt.Errorf("managed group is not visible to manager group")
	}
	return r.Store.Groups.CanGroupManageGroup(ctx, managerID, groupID)
}

// CanUserManageGroup is the resolver for the canUserManageGroup field.
func (r *queryResolver) CanUserManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	askingUserID := auth.UserIDFromContext(ctx)

	if askingUserID == nil {
		return false, auth.ErrNotAuthenticated
	}

	visibleToAsker, err := r.Store.Groups.IsGroupVisibleToUser(ctx, *askingUserID, groupID)
	if err != nil {
		return false, err
	}
	if !visibleToAsker {
		return false, models.ErrNoGroupOrWrongPermissions
	}
	return r.Store.Groups.CanUserManageGroup(ctx, managerID, groupID)
}

// AnonymousGroup returns gql.AnonymousGroupResolver implementation.
func (r *Resolver) AnonymousGroup() gql.AnonymousGroupResolver { return &anonymousGroupResolver{r} }

// Group returns gql.GroupResolver implementation.
func (r *Resolver) Group() gql.GroupResolver { return &groupResolver{r} }

// MembershipToGroup returns gql.MembershipToGroupResolver implementation.
func (r *Resolver) MembershipToGroup() gql.MembershipToGroupResolver {
	return &membershipToGroupResolver{r}
}

type (
	anonymousGroupResolver    struct{ *Resolver }
	groupResolver             struct{ *Resolver }
	membershipToGroupResolver struct{ *Resolver }
)
