package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
)

// GroupByID is the resolver for the groupById field.
func (r *queryResolver) GroupByID(ctx context.Context, id int) (*models.Group, error) {
	userID := ctx.Value(auth.UserContextKey{}).(int)

	group, err := r.Store.Groups.GetGroupById(ctx, id)
	if err != nil {
		return nil, err
	}
	visible, how, err := r.Store.Groups.IsGroupVisibleToUser(ctx, userID, group.Id)
	if err != nil {
		return nil, err
	}
	if !visible || how != models.GroupViewPermission_SeeAll {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}
	return group, nil
}

// MembersOfGroup is the resolver for the membersOfGroup field.
func (r *queryResolver) MembersOfGroup(ctx context.Context, groupID int) ([]*models.MembershipToGroup, error) {
	userID := ctx.Value(auth.UserContextKey{}).(int)
	visible, how, err := r.Store.Groups.IsGroupVisibleToUser(ctx, userID, groupID)
	if err != nil {
		return nil, err
	}
	if !visible || how != models.GroupViewPermission_SeeAll {
		return nil, fmt.Errorf("group does not exist or user does not have permission to see it")
	}

	// return
}

// IsUserInGroup is the resolver for the isUserInGroup field.
func (r *queryResolver) IsUserInGroup(ctx context.Context, userID int, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: IsUserInGroup - isUserInGroup"))
}

// IsUserInGroupDirectly is the resolver for the isUserInGroupDirectly field.
func (r *queryResolver) IsUserInGroupDirectly(ctx context.Context, userID int, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: IsUserInGroupDirectly - isUserInGroupDirectly"))
}

// CanGroupManageGroup is the resolver for the canGroupManageGroup field.
func (r *queryResolver) CanGroupManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: CanGroupManageGroup - canGroupManageGroup"))
}

// CanUserManageGroup is the resolver for the canUserManageGroup field.
func (r *queryResolver) CanUserManageGroup(ctx context.Context, managerID int, groupID int) (bool, error) {
	panic(fmt.Errorf("not implemented: CanUserManageGroup - canUserManageGroup"))
}
