package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// Zones is the resolver for the zones field.
func (r *makerspaceResolver) Zones(ctx context.Context, obj *models.Makerspace) ([]*models.Zone, error) {
	zones, err := r.Store.Zones.GetZonesByMakerspaceId(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	return zones, err
}

// Hours is the resolver for the hours field.
func (r *makerspaceResolver) Hours(ctx context.Context, obj *models.Makerspace) ([]models.MakerspaceHours, error) {
	default_hours, err := r.Store.Makerspaces.GetDefaultHours(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	hours := make([]models.MakerspaceHours, len(default_hours))
	for i, h := range default_hours {
		hours[i] = h
	}

	return hours, nil
}

// Managers is the resolver for the managers field.
func (r *makerspaceResolver) Managers(ctx context.Context, obj *models.Makerspace) ([]*models.User, error) {
	us, err := r.Store.Groups.UsersInAnonymousGroup(ctx, obj.ManagementAgroupId)
	if err != nil {
		return nil, err
	}

	return SliceToPtrSlice(us), nil
}

// ManagerSubgroups is the resolver for the managerSubgroups field.
func (r *makerspaceResolver) ManagerSubgroups(ctx context.Context, obj *models.Makerspace) ([]*models.Group, error) {
	if err := CanUserFromContextManageAnonymousGroup(r.Store, ctx, obj.ManagementAgroupId); err != nil {
		return nil, fmt.Errorf("cannot list manager subgroups: %w", err)
	}

	sgs, err := r.Store.Groups.GroupsInAnonymousGroup(ctx, obj.ManagementAgroupId)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(sgs), nil
}

// Staff is the resolver for the staff field.
func (r *makerspaceResolver) Staff(ctx context.Context, obj *models.Makerspace) ([]*models.User, error) {
	us, err := r.Store.Groups.UsersInAnonymousGroup(ctx, obj.StaffAgroupId)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(us), nil
}

// StaffSubgroups is the resolver for the staffSubgroups field.
func (r *makerspaceResolver) StaffSubgroups(ctx context.Context, obj *models.Makerspace) ([]*models.Group, error) {
	sgs, err := r.Store.Groups.GroupsInAnonymousGroup(ctx, obj.StaffAgroupId)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(sgs), nil
}

// CreateMakerspace is the resolver for the createMakerspace field.
func (r *mutationResolver) CreateMakerspace(ctx context.Context, name string, hidden bool) (int, error) {
	user := FullUserFromContext(r.Store, ctx)
	if user != nil {
		return 0, auth.ErrNotAuthenticated
	}
	id, err := r.Store.Makerspaces.CreateMakerspace(ctx, name, hidden)
	if err != nil {
		return 0, err
	}
	makerspace, err := r.Store.Makerspaces.GetMakerspaceById(ctx, id)
	if err != nil {
		return id, fmt.Errorf("failed to retrieve new makerspace")
	}
	r.Logger.AuditLog.CreateUnassociated("builtin.makerspace.create", "{user} created {makerspace)", user.LogEntity(), makerspace.LogEntity())

	return id, nil
}

// DeleteMakerspace is the resolver for the deleteMakerspace field.
func (r *mutationResolver) DeleteMakerspace(ctx context.Context, id int) (bool, error) {
	success, err := r.Store.Makerspaces.DeleteMakerspace(ctx, id)
	if err != nil {
		return success, err
	}

	return success, err
}

// Makerspace is the resolver for the makerspace field.
func (r *queryResolver) Makerspace(ctx context.Context, id int) (*models.Makerspace, error) {
	makerspace, err := r.Store.Makerspaces.GetMakerspaceById(ctx, id)
	if err != nil {
		return nil, err
	}

	return makerspace, nil
}

// Makerspace returns gql.MakerspaceResolver implementation.
func (r *Resolver) Makerspace() gql.MakerspaceResolver { return &makerspaceResolver{r} }

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type (
	makerspaceResolver struct{ *Resolver }
	mutationResolver   struct{ *Resolver }
	queryResolver      struct{ *Resolver }
)
