package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// Zones is the resolver for the zones field.
func (r *makerspaceResolver) Zones(ctx context.Context, obj *models.Makerspace) ([]*models.Zone, error) {
	zones, err := r.Store.Zones.GetZonesByMakerspaceId(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	return zones, err
}

// Hours is the resolver for the hours field.
func (r *makerspaceResolver) Hours(ctx context.Context, obj *models.Makerspace) ([]models.MakerspaceHours, error) {
	default_hours, err := r.Store.Makerspaces.GetDefaultHours(ctx, obj.Id)
	if err != nil {
		return nil, err
	}

	hours := make([]models.MakerspaceHours, len(default_hours))
	for i, h := range default_hours {
		hours[i] = h
	}

	return hours, nil
}

// CreateMakerspace is the resolver for the createMakerspace field.
func (r *mutationResolver) CreateMakerspace(ctx context.Context, name string, hidden bool) (int, error) {
	id, err := r.Store.Makerspaces.CreateMakerspace(ctx, name, hidden)
	if err != nil {
		return 0, err
	}

	return id, nil
}

// DeleteMakerspace is the resolver for the deleteMakerspace field.
func (r *mutationResolver) DeleteMakerspace(ctx context.Context, id int) (bool, error) {
	success, err := r.Store.Makerspaces.DeleteMakerspace(ctx, id)
	if err != nil {
		return success, err
	}

	return success, err
}

// Makerspace is the resolver for the makerspace field.
func (r *queryResolver) Makerspace(ctx context.Context, id int) (*models.Makerspace, error) {
	makerspace, err := r.Store.Makerspaces.GetMakerspaceById(ctx, id)
	if err != nil {
		return nil, err
	}

	return makerspace, nil
}

// Makerspace returns gql.MakerspaceResolver implementation.
func (r *Resolver) Makerspace() gql.MakerspaceResolver { return &makerspaceResolver{r} }

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

// Query returns gql.QueryResolver implementation.
func (r *Resolver) Query() gql.QueryResolver { return &queryResolver{r} }

type (
	makerspaceResolver struct{ *Resolver }
	mutationResolver   struct{ *Resolver }
	queryResolver      struct{ *Resolver }
)

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Thing(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Thing - thing"))
}
*/
