package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
	"make-backend/internal/gql"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*models.User, error) {
	return r.Store.Users.GetUserById(ctx, id)
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models.User, error) {
	userId := auth.UserIDFromContext(ctx)
	if userId == nil {
		return nil, nil
	}
	user, err := r.Store.Users.GetUserById(ctx, *userId)

	return user, err
}

// Groups is the resolver for the groups field.
func (r *userResolver) Groups(ctx context.Context, obj *models.User) ([]*models.Group, error) {
	userId := auth.UserIDFromContext(ctx)
	if userId == nil { // visitor in no groups
		return []*models.Group{}, nil
	}
	gs, err := r.Store.Groups.AllGroupsUserIsInAndVisibleToAsker(ctx, *userId)
	if err != nil {
		return nil, err
	}
	return SliceToPtrSlice(gs), nil
}

// AllGroups is the resolver for the allGroups field.
func (r *userResolver) AllGroups(ctx context.Context, obj *models.User) ([]*models.Group, error) {
	// get all groups visible to asker that the target user is in
	panic(fmt.Errorf("not implemented: AllGroups - allGroups"))
}

// User returns gql.UserResolver implementation.
func (r *Resolver) User() gql.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
