package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"fmt"
	"make-backend/internal/auth"
	"make-backend/internal/database/models"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, targetID int) (*models.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models.User, error) {
	userid := ctx.Value(auth.UserContextKey{}).(int)
	user, err := r.Store.Users.GetUserById(ctx, userid)

	return user, err
}
