// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: notify/interface.proto

package notify

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "make-backend/internal/plugins/common"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_notify_interface_proto protoreflect.FileDescriptor

const file_notify_interface_proto_rawDesc = "" +
	"\n" +
	"\x16notify/interface.proto\x12\x06notify\x1a\x13common/plugin.proto2N\n" +
	"\x12NotificationPlugin\x128\n" +
	"\x04Info\x12\x1c.common.PluginInitialMessage\x1a\x12.common.PluginInfoB&Z$make-backend/internal/plugins/notifyb\x06proto3"

var file_notify_interface_proto_goTypes = []any{
	(*common.PluginInitialMessage)(nil), // 0: common.PluginInitialMessage
	(*common.PluginInfo)(nil),           // 1: common.PluginInfo
}
var file_notify_interface_proto_depIdxs = []int32{
	0, // 0: notify.NotificationPlugin.Info:input_type -> common.PluginInitialMessage
	1, // 1: notify.NotificationPlugin.Info:output_type -> common.PluginInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_interface_proto_init() }
func file_notify_interface_proto_init() {
	if File_notify_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_interface_proto_rawDesc), len(file_notify_interface_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_interface_proto_goTypes,
		DependencyIndexes: file_notify_interface_proto_depIdxs,
	}.Build()
	File_notify_interface_proto = out.File
	file_notify_interface_proto_goTypes = nil
	file_notify_interface_proto_depIdxs = nil
}
