// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: notify/interface.proto

package notify

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "make-backend/internal/plugins/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationPlugin_Info_FullMethodName = "/notify.NotificationPlugin/Info"
)

// NotificationPluginClient is the client API for NotificationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationPluginClient interface {
	Info(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.PluginInfo, error)
}

type notificationPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationPluginClient(cc grpc.ClientConnInterface) NotificationPluginClient {
	return &notificationPluginClient{cc}
}

func (c *notificationPluginClient) Info(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.PluginInfo)
	err := c.cc.Invoke(ctx, NotificationPlugin_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationPluginServer is the server API for NotificationPlugin service.
// All implementations must embed UnimplementedNotificationPluginServer
// for forward compatibility.
type NotificationPluginServer interface {
	Info(context.Context, *common.Empty) (*common.PluginInfo, error)
	mustEmbedUnimplementedNotificationPluginServer()
}

// UnimplementedNotificationPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationPluginServer struct{}

func (UnimplementedNotificationPluginServer) Info(context.Context, *common.Empty) (*common.PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedNotificationPluginServer) mustEmbedUnimplementedNotificationPluginServer() {}
func (UnimplementedNotificationPluginServer) testEmbeddedByValue()                            {}

// UnsafeNotificationPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationPluginServer will
// result in compilation errors.
type UnsafeNotificationPluginServer interface {
	mustEmbedUnimplementedNotificationPluginServer()
}

func RegisterNotificationPluginServer(s grpc.ServiceRegistrar, srv NotificationPluginServer) {
	// If the following call panics, it indicates UnimplementedNotificationPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationPlugin_ServiceDesc, srv)
}

func _NotificationPlugin_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationPluginServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationPlugin_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationPluginServer).Info(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationPlugin_ServiceDesc is the grpc.ServiceDesc for NotificationPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotificationPlugin",
	HandlerType: (*NotificationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _NotificationPlugin_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify/interface.proto",
}
