// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Announcement struct {
	ID           int    `json:"id"`
	Title        string `json:"title"`
	Body         string `json:"body"`
	MakerspaceID *int   `json:"makerspace_id,omitempty"`
}

type Query struct {
}
