// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Makerspace struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Subtitle    string `json:"subtitle"`
	Description string `json:"description"`
	DocsURL     string `json:"docs_url"`
	ImageID     *int32 `json:"image_id,omitempty"`
	Hidden      bool   `json:"hidden"`
}

type Query struct {
}

type User struct {
	ID            int       `json:"id"`
	Username      string    `json:"username"`
	Firstname     string    `json:"firstname"`
	Lastname      string    `json:"lastname"`
	Pronouns      string    `json:"pronouns"`
	JoinDate      time.Time `json:"join_date"`
	SetupComplete bool      `json:"setup_complete"`
	Archived      bool      `json:"archived"`
	Notes         string    `json:"notes"`
	Admin         bool      `json:"admin"`
	ForceArchive  *bool     `json:"force_archive,omitempty"`
	CardTag       string    `json:"card_tag"`
}
