// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthProvider struct {
	Name     string `json:"Name"`
	ImageURL string `json:"ImageURL"`
	PluginID string `json:"PluginId"`
}

type Mutation struct {
}

type Query struct {
}
